// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agleyxrkkdizxietpehj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnbGV5eHJra2RpenhpZXRwZWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0OTM3NzMsImV4cCI6MjA1MzA2OTc3M30.9PDbBzWswagLj_5lGrV5WV2-l27366iBCG22kszdG7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);